### PR TITLE
Feature spire

### PR DESCRIPTION
**Pull request by pxp928**
**Fixes issue:**

**Description:**
Added spire support (3rd PR from Boxboat). Updated made to the CLI, MakeFile and Readme to capture the changes. Added Dockerfile and docker-compose file to bring up the spire infrastructure on docker to allow for testing. New test-infra folder has been added to bring up spire server and spire agent locally for testing. MakeFile has been updated and tests have been added utilize the spire functionality. ReadMe and CLI updated with the optional spire flags and corresponding code to get SVID from the spire agent.

**Please verify and check that the pull request fulfills the following
requirements:**

- [x] Tests have been added for the bug fix or new feature
- [x] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by mikhailswift** [comment]
I had to make some changes to the SPIRE code when using it.  We don't need to or want to connect to SPIRE during verification but instead need to fetch the intermediates when requesting the SVID during record and run. 

Check out https://github.com/mikhailswift/in-toto-golang/tree/spiffe

**Comment by pxp928** [comment]
> I had to make some changes to the SPIRE code when using it. We don't need to or want to connect to SPIRE during verification but instead need to fetch the intermediates when requesting the SVID during record and run.
> 
> Also getting the trust bundle is not desired and I misunderstood when I wrote that function originally. SPIRE ships the intermediates with the SVID, the first certificate in the SVID's certificate array is the leaf and anything afterward are intermediates. The trust bundle is the root certificate, which should be in the signed layout.
> 
> Check out https://github.com/mikhailswift/in-toto-golang/tree/spiffe
> 
> I've also modified the code to make it more testable, though I haven't written tests yet.

Hey Mikhail! Do we want to work together to merge the branches together and get the tests created before we PR into in-toto:master?

**Comment by mikhailswift** [comment]
That would be good :)

**Comment by pxp928** [comment]
Closing PR to work with Mikhail to improve the Spire integration.

**Pull request closed without merging**
