### PR TITLE
make .metadata optional in Provenance statement

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

*Please fill in the fields below to submit a pull request.  The more
information that is provided, the better.*

**Fixes issue #**:

**Description of pull request**:

We (I and @Dentrax) saw the `.metadata` section is defined as an optional field in the [fields](https://github.com/in-toto/attestation/blob/main/spec/predicates/provenance.md#fields) section of the Provenance documentation, so we should add the `omitempty` tag to it too. This PR aims to fix this problem.

**Please verify and check that the pull request fulfills the following
requirements**:

- [x] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Review by adityasaky — CHANGES_REQUESTED** [review]
Hi @developer-guy, thanks for the patch! I'm not 100% certain this fixes it the way we want it to, though, because it's a struct field. I think we want to also change `Metadata ProvenanceMetadata` to `Metadata *ProvenanceMetadata`, because the struct itself doesn't have an empty value. If we want the default values within `ProvenanceMetadata` I suppose this is okay, though I haven't followed this into the other structs. :)

See: https://play.golang.org/p/ijyRb-By9sN here, the metadata field is still printed, while in https://play.golang.org/p/x0ajUdtSabJ it is not.

**Comment by developer-guy** [comment]
> Hi @developer-guy, thanks for the patch! I'm not 100% certain this fixes it the way we want it to, though, because it's a struct field. I think we want to also change `Metadata ProvenanceMetadata` to `Metadata *ProvenanceMetadata`, because the struct itself doesn't have an empty value. If we want the default values within `ProvenanceMetadata` I suppose this is okay, though I haven't followed this into the other structs. :)
> 
> See: https://play.golang.org/p/ijyRb-By9sN here, the metadata field is still printed, while in https://play.golang.org/p/x0ajUdtSabJ it is not.

thank you so much for warning us @adityasaky, we forgot to do it, but now it should be ok, I updated the code according to your changes, thank you so much 🥳🙋🏻‍♂️

**Comment by adityasaky** [comment]
Looks like the tests need to be updated to match the change in field. :)

**Comment by developer-guy** [comment]
> Looks like the tests need to be updated to match the change in field. :)

fixed, thank you so much again, sorry about all the mistakes 🤦🏻‍♂️

**Comment by adityasaky** [comment]
Thanks @developer-guy, and no problem at all. Before we merge, I just want to check with / give a heads up to @dlorenc and @SantiagoTorres. We don't want to break something without warning...:)

**Comment by developer-guy** [comment]
okay, make sense @adityasaky 🤝🙋🏻‍♂️

**Comment by dlorenc** [comment]
+1 from me!

**Comment by SantiagoTorres** [comment]
It also LGTM :)

**Comment by adityasaky** [comment]
Thanks!

**Comment by adityasaky** [comment]
And thanks again, @developer-guy! :)

**Comment by developer-guy** [comment]
Thank you so much folks!! ❤️🙋🏻‍♂️

**Pull request merged**
