### PR TITLE
ci/go linting

### PR DESCRIPTION
**Pull request by kevholmes**
**Fixes issue:**

https://github.com/in-toto/in-toto-golang/issues/74

**Description:**

This PR adds a new `ci` Actions workflow to the in-toto-golang repo. It only runs on `pull_request` and any subsequent commits to a PR before it is merged. The workflow utilizes [golangci](https://golangci-lint.run/) and its corresponding GitHub [Action](https://github.com/marketplace/actions/run-golangci-lint). The Action is configured to only highlight new issues in submitted PRs via the `only-new-issues: true` switch located within `.github/workflows/ci.yml`. This ensures that checks are only run on the code being submitted in a PR, not all code within the project. This will allow you to turn on Go code linting now, and over time the existing linter failures described [here](https://github.com/in-toto/in-toto-golang/issues/74#issue-683061115) can be remediated as time allows.

**Please verify and check that the pull request fulfills the following
requirements:**

- [ x] Tests have been added for the bug fix or new feature
- [ x] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by kevholmes** [comment]
Feedback welcome, tagging maintainers for Viz since I seem to be unable to tag them for a `Review` @SantiagoTorres @shibumi @adityasaky @lukpueh

**Comment by shibumi** [comment]
Ah this is awesome. I always wanted to take a look on golangci for linting. In the past we thought about golint, but golint enforces a full linting. Looks like golangci allows activating only a few linting features. Nice.

**Review by shibumi — APPROVED** [review]

**Comment by kevholmes** [comment]
> Ah this is awesome. I always wanted to take a look on golangci for linting. In the past we thought about golint, but golint enforces a full linting. Looks like golangci allows activating only a few linting features. Nice.

Glad you like it! I have been setting a bunch of these up lately for clients and I really like how easy it is to get started with some good CI tool integrations. There are a ton of other linters available but I just pinned the default set into `.golangci.yml` lots of other config options like ignoring specific files, entire folders, or rule sets for a particular analysis tool. I would also suggest adding a markdown linter to keep documentation changes under wraps - I could create a ticket and follow-up PR for that also if there's interest. I'm working on an open source challenge at work and have some time to help out.

**Review by adityasaky — APPROVED** [review]

**Comment by adityasaky** [comment]
Thanks, @kevholmes, much appreciated!

**Pull request merged**
