### PR TITLE
Split the EnvelopeSigner struct into an EnvelopeVerifier struct.

### PR DESCRIPTION
**Pull request by dlorenc**
There are use cases where you want to verify without access to the private key,
so this makes it easier!

*Please fill in the fields below to submit a pull request.  The more
information that is provided, the better.*

cc @kommendorkapten

### CODE REVIEW

**Comment by kommendorkapten** [comment]
Good deal! Nice job @dlorenc 👍

**Review by shibumi — APPROVED** [review]

**Comment by shibumi** [comment]
LGTM, good work @dlorenc

**Comment by dlorenc** [comment]
Thanks for the fast reviews!

**Comment by SantiagoTorres** [comment]
LGTM!

**Pull request merged**
