### PR TITLE
Updated according to attestation release v0.1.0.

### PR DESCRIPTION
**Pull request by kommendorkapten**
(cherry picked from commit 826ab7cc966c45921b06d945671531e71048716a)

*Please fill in the fields below to submit a pull request.  The more
information that is provided, the better.*

**Fixes issue #**:
Updates the ite-6 branch with v0.1.0 of attestation spec: https://github.com/in-toto/attestation/tree/v0.1.0

**Description of pull request**:

**Please verify and check that the pull request fulfills the following
requirements**:

- [x] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by kommendorkapten** [comment]
I worked on updating #100 to match the v0.1.0 release yesterday, but never got to commit it, so here it is :)
@marklodato @SantiagoTorres @dlorenc

**Review by dlorenc — APPROVED** [review]
Awesome!

**Review by shibumi — APPROVED** [review]

**Comment by shibumi** [comment]
Awesome! Thanks for your contribution. Good work!

**Comment by shibumi** [comment]
@adityasaky  @SantiagoTorres  do you two want to have a look on this before we merge this?

**Comment by dlorenc** [comment]
@SantiagoTorres any thoughts on this one? It looks ready to me.

**Comment by shibumi** [comment]
@dlorenc  I talked with @SantiagoTorres  we can merge this one here :)

**Pull request merged**
