### PR TITLE
added small example to the readme

### PR DESCRIPTION
**Pull request by omerlh**
I just spent some time digging in the tests to figure how to use this lib, so I added a small example to the readme - to help others.

### CODE REVIEW

**Comment by shibumi** [comment]
This is really cool @omerlh. Very good idea.

Maybe we should include such examples in our code documentation as well. Go allows examples in the "docstrings", IIRC.

**Comment by omerlh** [comment]
Yes please! I have full example with steps for a typical nodeJS app that I can share

**Comment by shibumi** [comment]
@omerlh  Maybe we should have a dedicated docs or examples directory. @SantiagoTorres  what do you think?

**Comment by SantiagoTorres** [comment]
I like this! yeah I think we should have an examples dir...

I'll merge this as-is as part of the README. Thank you @omerlh @shibumi!

**Pull request merged**
