### PR TITLE
Data structures for generalized link formats/ITE-6

### PR DESCRIPTION
**Pull request by kommendorkapten**
*Please fill in the fields below to submit a pull request.  The more
information that is provided, the better.*

**Fixes issue #**:
Adds the data types for the generalized link format as described in this PR https://github.com/in-toto/ITE/pull/15 (ITE-6).

**Description of pull request**:
Only the data types are added in this PR. This includes the "Envelope", but not implementation for the serialization. I will work on the implementation for the SSL signing spec/ITE-5 in the coming weeks.

**Please verify and check that the pull request fulfills the following
requirements**:

- [*] Tests have been added for the bug fix or new feature
- [*] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by MarkLodato** [comment]
Note that the spec is still in flight. I plan to release a v1 by the end of the month. I don't expect any changes, but technically the spec isn't released yet. https://github.com/in-toto/attestation/issues/1

**Review by shibumi — APPROVED** [review]

**Comment by shibumi** [comment]
Thanks for the PR. From my side of view the PR looks fine and could be merged.

Did you find something @SantiagoTorres  @adityasaky?

**Comment by kommendorkapten** [comment]
@shibumi From my side it makes sense to wait until ITE-6 is released to minimize any extra work required (if ITE-6 will be changed).

**Comment by shibumi** [comment]
@kommendorkapten  makes sense. :+1:

**Comment by MarkLodato** [comment]
I just tagged v0.1.0 of https://github.com/in-toto/attestation. The spec still hasn't been accepted as part of ITE-6 yet, and there might be future 0.x releases with significant changes, but at least it is a released version that won't change meaning.

**Comment by shibumi** [comment]
@MarkLodato  Do we have an ETA for ITE-6 already?

**Comment by MarkLodato** [comment]
> Do we have an ETA for ITE-6 already?

@SantiagoTorres may have a better idea. Maybe end of May? The two main blockers are:
1. Figuring out how ITE-6 attestations work with existing layouts.
2. Being reasonably happy with the design of the attestations, such that in-toto will support it long-term.

I'll work on (1) in the coming weeks, but (2) will likely take some time. I don't know what the bar is for in-toto.

**Comment by dlorenc** [comment]
@SantiagoTorres I'd like to get this committed "somewhere" to start playing around with it in tektoncd/chains. Are you comfortable with it here even though the spec is only v0.1? I can make another repo somewhere else we can iterate on if you prefer.

I think it'll help validate the formats if we can get it working in chains and other systems, which will help build confidence as we firm up the spec.

**Comment by SantiagoTorres** [comment]
Hmm, I think we could commit it and keep in some sort of -next branch/tag, would that work?

**Comment by dlorenc** [comment]
> Hmm, I think we could commit it and keep in some sort of -next branch/tag, would that work?

SGTM! Another branch would be great.

**Comment by SantiagoTorres** [comment]
I'm merging to a branch called ite-6, we can move things around once the spec crystallizes more

**Comment by dlorenc** [comment]
Amazing! Thanks!

**Comment by shibumi** [comment]
@dlorenc can you link your changes/tests for tekton here? I am really interested in this, because we are running tekton as CI/CD system in my company already.

**Comment by shibumi** [comment]
@SantiagoTorres  maybe we should do a short in-toto-golang meeting in the next weeks for discussing versions bumps for in-toto-golang. I mean if we merge ITE5 and ITE6 we should definitely schedule a new release (except you have anything in your mind that should be in the next version).

**Comment by dlorenc** [comment]
Sure! The basic is to add support for automatically generating ite-6 formatted provenance for all pipeline/taskruns as part of tekton chains.

Here was an old draft pr that needs to get updated: https://github.com/tektoncd/chains/pull/13

**Comment by kommendorkapten** [comment]
@shibumi We are also working on ITE-6 support for chains (@dlorenc is aware), we have our WIP branch here: https://github.com/tektoncd/chains/compare/main...solarwinds:ite6
It's a few weeks old, and ITE-6 has been updated since that, so I will update our chains branch to use the new schema.

**Pull request merged**
