### PR TITLE
Update Go versions used in CI

### PR DESCRIPTION
**Pull request by adityasaky**
Switch from testing Go `1.16.x`, `1.17.x` to `1.17.x`, `1.18.x`, `1.19.x`.

### CODE REVIEW

**Comment by shibumi** [comment]
I have restarted the failing job. If it still fails, we might have to look into this.

**Comment by shibumi** [comment]
> 1.17.x, 1.18.x, 1.19.x

Does it make sense to support 3 versions? Even Go supports only 2 LTS releases in a row.

**Comment by shibumi** [comment]
That's weird. This line fails: `run: test -z $(go fmt ./...)`, but why is this succeeding on every other OS?

**Comment by shibumi** [comment]
Can you manually run `go fmt ...` on a Linux system and see if code needs to be formatted?

**Comment by pxp928** [comment]
@adityasaky Did some testing and seems like 1.19 formats the code a bit differently. Did a local test -> https://github.com/pxp928/in-toto-golang/pull/2 and it does need some files to be formatted.

**Comment by adityasaky** [comment]
Yes, I just expected the error to be different but thinking about it some more, the output of fmt is probably too long as an argument to `test`.

**Comment by shibumi** [comment]
> I thought we were following the previous, current, next model, but I'm okay with just doing two. 😄

But Isn't Go 1.19 already released? If we follow the 'next' model this would be a release candidate of Go 1.20. 🤔

**Comment by adityasaky** [comment]
Good point. Do we switch to 1.18 and 1.19 then? And fmt only on latest?

**Comment by shibumi** [comment]
> Good point. Do we switch to 1.18 and 1.19 then? And fmt only on latest?

Yes, I would suggest doing this. It sucks that they changed the format.. but we have to live with it.

**Review by shibumi — APPROVED** [review]
LGTM

**Pull request merged**
