### PR TITLE
Add custom CWD for inspections

### PR DESCRIPTION
**Pull request by SantiagoTorres**
*Please fill in the fields below to submit a pull request.  The more
information that is provided, the better.*

**Fixes issue #**: #46

**Description of pull request**: This is a followup after further requests for the feature. In short, the option to select a local directory from where the inspections are run may help keeping things tidy at the time of executing them. Worthwhile mentioning, a stronger security mechanism (i.e., an actual sandbox) may be desirable in the long-run...

 I'm frankly amazed that this still merges 2 years after the fact, so I'd like to review and make sure there are no breaking changes that aren't immediately obvious.

Kudos to @radu-matei for this. I'm just the messenger.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] Tests have been added for the bug fix or new feature
- [x] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by shibumi** [comment]
@SantiagoTorres  can you run `go fmt` and commit? This should fix the build errors.

**Comment by scottbuckel** [comment]
> I'm frankly amazed that this still merges 2 years after the fact, so I'd like to review and make sure there are no breaking changes that aren't immediately obvious.

@SantiagoTorres I merged in-toto:master into Radu's branch a few weeks ago, with some changes to make it work. My commits d512e32, e4fb809, and c75f396 should include those changes. :)

**Comment by SantiagoTorres** [comment]
ah, thank you @scottbuckel !

**Comment by shibumi** [comment]
@radu-matei maybe it's easier if you just re-open the PR or @scottbuckel ? Then we can get this merged :)

**Comment by SantiagoTorres** [comment]
Closing in favor of #104 for the sake of my own sanity

**Pull request closed without merging**
