### PR TITLE
Handle ctx for go-sslib

### PR DESCRIPTION
**Pull request by adityasaky**
**Fixes issue:** N/A

**Description:**

This updates in-toto-golang to support passing in context when using DSSE APIs (see: https://github.com/secure-systems-lab/go-securesystemslib/pull/34).

**Please verify and check that the pull request fulfills the following
requirements:**

- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by adityasaky** [comment]
@shibumi and @pxp928, can you check if this makes sense?

**Comment by shibumi** [comment]
This makes sense for me, did you run the tests? If your PR is a draft, the CI jobs won't run :)

**Comment by adityasaky** [comment]
They do run, https://github.com/in-toto/in-toto-golang/actions/runs/4196053158, and they've passed.

**Review by pxp928 — APPROVED** [review]
LGTM

**Pull request merged**
