### PR TITLE
Provide SLSA Provenance by major version only

### PR DESCRIPTION
**Pull request by adityasaky**
**Fixes issue:** N/A

https://github.com/in-toto/in-toto-golang/pull/221#discussion_r1173592539

**Description:**

Moves SLSA Provenance to v1 directory instead of v1.0. The package is already `v1` only, this removes any ambiguity / expectations of separately maintained models for minor or patch updates of the Provenance spec.

**Please verify and check that the pull request fulfills the following
requirements:**

- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by adityasaky** [comment]
@chuangw6, @asraa FYI

**Review by pxp928 — APPROVED** [review]
LGTM

**Comment by asraa** [comment]
Thank you so much! I've been OOO for the past two weeks, so catching up now.

**Comment by adityasaky** [comment]
Neat! We've cut a release with this since. :smile:

**Pull request merged**
