### PR TITLE
feat: auto-completion support

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

**Fixes issue:**

**Description:**

add auto-completion support

cc: @shibumi 

**Please verify and check that the pull request fulfills the following
requirements:**

- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

ezgif com-gif-maker

### CODE REVIEW

**Comment by shibumi** [comment]
@developer-guy  can you have a look on the failing CI tests?
The log messages are weird:

```
  Error: Error return value of `` is not checked (errcheck)
  Error: Error return value of `` is not checked (errcheck)
  Error: Error return value of `` is not checked (errcheck)
  
  Error: issues found
```

**Comment by developer-guy** [comment]
> @developer-guy can you have a look on the failing CI tests? The log messages are weird:
> 
> ```
>   Error: Error return value of `` is not checked (errcheck)
>   Error: Error return value of `` is not checked (errcheck)
>   Error: Error return value of `` is not checked (errcheck)
>   
>   Error: issues found
> ```

looks good right now @shibumi, thank you 🤝

**Review by shibumi — APPROVED** [review]

**Comment by shibumi** [comment]
@developer-guy  Thank you :)

**Comment by developer-guy** [comment]
> @developer-guy Thank you :)

it's my pleasure, thank you so much for merging🥳🤝

**Pull request merged**
