### PR TITLE
fix: do not alter content when hashing files

### PR DESCRIPTION
**Pull request by shibumi**
**Fixes issue:**

None

**Description:**
Before we have normalized lines for supporting different
operating systems. The line normalization led to altered
byte segments in BLOBs. This patch disables the line normalization
feature for now, adds a test and removes windows CI runs.

**Please verify and check that the pull request fulfills the following
requirements:**

- [x] Tests have been added for the bug fix or new feature
- [x] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by shibumi** [comment]
@adityasaky  I forgot one thing.. I switched to 'alice.pub' as test file.. but alice.pub is not a binary.. so the test does not make sense any more. Let me use the test tar.gz file instead  for the test.

**Comment by shibumi** [comment]
Ok, now it's ready for review...

**Comment by shibumi** [comment]
@adityasaky  and me just realized that we have no issues with the foo.tar.gz file, because this file does not have the corresponding byte segments... We have to add another test file that triggers the bug (when line normalization is enabled).

**Comment by shibumi** [comment]
I have added a helloworld binary compiled with Go 1.17 and I can confirm this time the bug gets triggered, because there are windows-like line breaks as byte segments in this file.

**Comment by shibumi** [comment]
@adityasaky  This is ready now. Note to the student who should work on this: If we add another flag to the function we should probably try to toggle it in the test function and test the reproduction of the bug.

**Review by adityasaky — APPROVED** [review]
LGTM, thanks @shibumi!

**Pull request merged**
